name = "EmergentEcology"
uuid = "71e8e4c4-623a-481a-8cc0-00a7a97f48c3"
authors = ["nondairyneutrino <chapmann19@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
